########################################
# CONSTANTS
########################################
uint8 MOVING_TYPE_IDLE = 0
uint8 MOVING_TYPE_LEFT = 1
uint8 MOVING_TYPE_RIGHT = 2
uint8 MOVING_TYPE_FORWARD = 3
uint8 MOVING_TYPE_BACKWARD = 4

########################################
# Messages
########################################
uint8 moving_type
float32 moving_value_angular
float32 moving_value_linear